version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  postgres:
    image: "postgres:9.6"
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ${BASE_PATH:-/data}/pgdata:/var/lib/postgresql/data
      - /var/backup/pgsql:/var/backup/pgsql
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:3"
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - .env

  memcached:
    image: "memcached:alpine"
    restart: unless-stopped
    logging: *default-logging

  awx_web:
    image: "ansible/awx_web:9.0.1"
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.awx.entrypoints=https
      - traefik.http.routers.awx.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-route53}
      - traefik.http.routers.awx.tls=true
      - traefik.http.routers.awx.rule=${AWX_URL_CONFIG:-Host(`awx.infra.naturalis.nl`)}
    volumes:
      - "${BASE_PATH:-/data}/SECRET_KEY:/etc/tower/SECRET_KEY"
    hostname: awxweb
    user: root
    env_file:
      - .env

  awx_task:
    image: "ansible/awx_task:9.0.1"
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - rabbitmq
      - memcached
      - awx_web
      - postgres
    volumes:
      - "${BASE_PATH:-/data}/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "${BASE_PATH:-/data}/ansible:/data/ansible"
    hostname: awx
    user: root
    env_file:
      - .env

  traefik:
    image: traefik:2.0.5
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - web
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    logging: *default-logging

networks:
    default:
    web:
        external: true
